theme: jekyll-theme-minimal
<h1>Welcome to Sam Appelbaum's homepage!</h1>

<p>I went to Glen Ridge High School. I was a part of their robotics team and eventually became the captain of programming. My hobbies include watching anime and playing videogames. </p>

<p>The rit SE website can be found <span herf="https://www.rit.edu/computing/department-software-engineering">here</span>.</p>

<p>I would like to learn about:</p>
<ul>
  <li>Teamwork</li>
  <li>The development process</li>
  <li></li>
</ul>  
